---
- hosts: vm2
  sudo: yes
  sudo_user: root

  roles:
    - common
    - { role: firewalld, tags: ['firewall'] }
    - { role: mariadb, tags: ['mariadb', 'database'] }
    - { role: nginx, tags: ['nginx'] }

- include: playbooks/db-dev.yml
- include: playbooks/network-dev.yml
- include: playbooks/db-prod.yml
- include: playbooks/network-prod.yml
