---
- name: restart nginx
  service: name=nginx state=restarted

- name: daemon reload
  command: systemctl daemon-reload

- name: "restart gunicorn-{{ sitename }}"
  service: name="gunicorn-{{ sitename }}" state=restarted
