---
# tasks file for common
- include_vars: private.yml

- name: Install EPEL repo
  yum: name=epel-release state=present
  tags:
    - yum
    - pkg
    - epel

- name: Install system dependencies
  yum: name={{ item }} state=present
  with_items:
    - vim
    - tar
    - policycoreutils-python
    - git
    - net-tools
    - python-devel
    - gcc
    - libxslt-devel
    - libxml2-devel
    - libjpeg-turbo-devel
  tags:
    - yum
    - pkg

- name: Add deploy group
  group: name=deploy state=present

- name: Add admins
  user: name={{ item.name }} group={{ item.name }} groups=wheel state=present
  with_items: admins

- name: Add ssh keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: admins

- name: Create satnogs user
  user:
    name: satnogs
    groups: nginx
  tags:
    - base
    - user
    - provision
    - app

- name: Create /var/run/satnogs dir
  file:
    path: /var/run/satnogs
    state: directory
    owner: satnogs
    group: satnogs
    mode: 0755

- name: Copy tmpfiles for /var/run/tmpfiles
  copy:
    src: satnogs-tmpfiles.d
    dest: /etc/tmpfiles.d/satnogs.conf
    owner: root
    group: root
    mode: 0644
