---
- hosts: vm2
  sudo: yes
  sudo_user: root

  vars_files:
    - roles/mariadb/vars/private.yml

  vars:
    var_www: '/var/www/satnogs'
    app_dir: '{{ var_www }}/db/prod/app'
    venv_dir: '{{ var_www }}/db/prod/venv'
    sitename: 'db'
    socket_dir: '/var/run/satnogs/{{ sitename }}.sock'
    requirements_file: '{{ app_dir }}/requirements/production.txt'
    django_settings: 'db.settings.production'
    db_prod: true

  roles:
    - { role: satnogs, tags: ['db_prod', 'db'] }
