---
- hosts: vm2
  sudo: yes
  sudo_user: root

  vars_files:
    - roles/mariadb/vars/private.yml

  vars:
    var_www: '/var/www/satnogs'
    app_dir: '{{ var_www }}/network/dev/app'
    venv_dir: '{{ var_www }}/network/dev/venv'
    sitename: 'network-dev'
    socket_dir: '/var/run/satnogs/{{ sitename }}.sock'
    requirements_file: '{{ app_dir }}/requirements/production.txt'
    django_settings: 'network.settings.stage'
    net_dev: true

  roles:
    - { role: satnogs, tags: ['network_dev', 'network'] }
