---
- hosts: all
  sudo: yes
  sudo_user: root

  vars_files:
    - roles/mariadb/vars/private.yml

  vars:
    var_www: '/var/www/satnogs'
    app_dir: '{{ var_www }}/network/dev/app'
    venv_dir: '{{ var_www }}/network/dev/venv'
    sitename: 'network-dev'
    socket_dir: '/var/run/satnogs/{{ sitename }}.sock'
    requirements_file: '{{ app_dir }}/requirements/production.txt'
    repo_url: https://github.com/satnogs/satnogs-network.git
    repo_branch: dev
    django_settings: 'network.settings.stage'
    net_dev: true
    db_dev: false
    db_prod: false
    net_prod: false

  roles:
    - { role: satnogs, tags: ['network_dev', 'network'] }
