---
- hosts: vm2
  sudo: yes
  sudo_user: root

  roles:
    - { role: satnogs, tags: ['network_prod', 'network'] }

  vars:
    var_www: '/var/www/satnogs'
    app_dir: '{{ var_www }}/network/prod/app'
    venv_dir: '{{ var_www }}/network/prod/venv'
    sitename: 'network'
    socket_dir: '/var/run/satnogs/{{ sitename }}.sock'
    requirements_file: '{{ app_dir }}/requirements/production.txt'
